### PR TITLE
Code of Conduct file

### PR DESCRIPTION
**Pull request by david-cvp**
Adding new code of conduct file:

This code of conduct is based off the draft EPA code of conduct that I obtained from Joe T.

I added an "Intro" section, improved readability across the entire document by cleaning up long or unclear sentences, and added some additional information from the referenced code of conducts from GSA/CFPB.

@ibarra-michelle @maheese @jthomp13 - please review this code of conduct and add comments if anything is unclear or should be modified.

Once approved, the code of conduct will be added to all of our repositories.

Thanks!

### CODE REVIEW

**Review by jwhitehead77 — APPROVED** [review]

**Comment by maheese** [comment]
This looks fine to me.  @ibarra-michelle or @jthomp13 do you have any comments?

**Comment by ibarra-michelle** [comment]
Looks good to me. @jthomp13 ?

**Comment by david-cvp** [comment]
12/4 Updated link to EPA comment policy

@jthomp13 Please let me know if this code of conduct looks good and I'll add it to all of our repos

**Comment by jthomp13** [comment]
Looks good to me.

**Review by jthomp13 — APPROVED** [review]

**Pull request merged**
